### ISSUE TITLE
storage_engines的parameters参数，启动时报ClassCastException

### ISSUE THREAD

**Issue by wangzihaogithub** [lealone/Lealone-Docs#10]
这是我在lealone.yaml里写的配置。

storage_engines:
  - name: AOSE
    enabled: true
    parameters: {
      cacheSize: 1677721600,
      pageSplitSize: 16777216,
      compress: 2
}

Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.lealone.storage.aose.btree.BTreeStorage.getIntValue(BTreeStorage.java:102)
	at org.lealone.storage.aose.btree.BTreeStorage.<init>(BTreeStorage.java:67)
	at org.lealone.storage.aose.btree.BTreeMap.<init>(BTreeMap.java:90)
	at org.lealone.storage.aose.AOStorage.openBTreeMap(AOStorage.java:82)

**Comment by wangzihaogithub** [comment]
我在代码里，加上了Integer.valueOf，使下面的参数生效了， 但是发现sql运行的结果不对了，然后我又改回去，恢复不了了，这个参数不能动态调整吗？
  
          
              加上后Integer.valueOf， 使参数生效。
              private int getIntValue(String key, int defaultValue) {
                  Object value = map.getConfig(key);
                  return value != null ? (Integer) Integer.valueOf(String.valueOf(value)) : defaultValue;
              }          



            然后先这样加了参数
            parameters: {
                cacheSize: 1677721600,
                pageSplitSize: 16777216,
                compress: 2
            }
            
            发现查询结果不对了，然后这样改回去，查询结果还是不对了，之前还好好的
            parameters: {
              #  cacheSize: 1677721600,
              #  pageSplitSize: 16777216,
               # compress: 2
            }





<img width="1101" alt="image" src="https://user-images.githubusercontent.com/18204507/194073961-90634321-5fe4-4bf2-91e4-9e29f6265c2b.png">


<img width="1189" alt="image" src="https://user-images.githubusercontent.com/18204507/194074821-69137b68-31b5-460f-bf8d-72ecf2ea549c.png">

**Comment by wangzihaogithub** [comment]
这个是第一次用没加参数时的。

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/18204507/194075763-c32a0f53-2676-40cb-8b31-496ba0473023.png">

**Comment by wangzihaogithub** [comment]
可以了 谢谢
