### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by marsapolo** [lealone/Lealone-Docs#2]
Lealone version: 5.0.0-SNAPSHOT
Loading config from file:/Users/marklee/Downloads/lealone-5.0.0/conf/lealone.yaml
Base dir: ../data
Init storage engines: 8 ms
Init transaction engines: 102 ms
Init sql engines: 2 ms
Init protocol server engines: 45 ms
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.lealone.db.DataBuffer.getAndFlipBuffer(DataBuffer.java:489)
	at org.lealone.transaction.aote.log.UndoLog.toRedoLogRecordBuffer(UndoLog.java:120)
	at org.lealone.transaction.aote.AMTransaction.createLocalTransactionRedoLogRecord(AMTransaction.java:223)
	at org.lealone.transaction.aote.AMTransaction.writeRedoLog(AMTransaction.java:258)
	at org.lealone.transaction.aote.AMTransaction.commitLocal(AMTransaction.java:294)
	at org.lealone.transaction.aote.AMTransaction.commit(AMTransaction.java:284)
	at org.lealone.db.session.ServerSession.commit(ServerSession.java:573)
	at org.lealone.db.session.ServerSession.commit(ServerSession.java:542)
	at org.lealone.db.session.ServerSession.stopCurrentCommand(ServerSession.java:896)
	at org.lealone.sql.executor.YieldableBase.stop(YieldableBase.java:193)
	at org.lealone.sql.executor.YieldableBase.run(YieldableBase.java:117)
	at org.lealone.sql.StatementBase.syncExecute(StatementBase.java:532)
	at org.lealone.sql.StatementBase.executeUpdate(StatementBase.java:629)
	at org.lealone.sql.StatementBase.executeUpdate(StatementBase.java:595)
	at org.lealone.db.Database.createRootUserIfNotExists(Database.java:2162)
	at org.lealone.db.LealoneDatabase.<init>(LealoneDatabase.java:55)
	at org.lealone.db.LealoneDatabase.<clinit>(LealoneDatabase.java:32)
	at org.lealone.main.Lealone.init(Lealone.java:120)
	at org.lealone.main.Lealone.run(Lealone.java:61)
	at org.lealone.main.Lealone.main(Lealone.java:42)
Exception in thread "CheckpointService" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at org.lealone.db.DataBuffer.grow(DataBuffer.java:547)
	at org.lealone.db.DataBuffer.ensureCapacity(DataBuffer.java:523)
	at org.lealone.db.DataBuffer.limit(DataBuffer.java:375)
	at org.lealone.storage.aose.btree.chunk.Chunk.write(Chunk.java:269)
	at org.lealone.storage.aose.btree.BTreeStorage.executeSave(BTreeStorage.java:419)
	at org.lealone.storage.aose.btree.BTreeStorage.save(BTreeStorage.java:390)
	at org.lealone.storage.aose.btree.BTreeMap.save(BTreeMap.java:548)
	at org.lealone.transaction.aote.AMTransactionEngine$CheckpointService.checkpoint(AMTransactionEngine.java:362)
	at org.lealone.transaction.aote.AMTransactionEngine$CheckpointService.run(AMTransactionEngine.java:380)
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: Could not initialize class org.lealone.db.LealoneDatabase
	at org.lealone.db.Database.close(Database.java:1216)
	at org.lealone.db.DatabaseCloser.run(DatabaseCloser.java:64)

**Comment by marsapolo** [comment]
MAC OS

**Comment by codefollower** [comment]
那个 lealone-5.0.0.zip 和 lealone-5.0.0.tar.gz 是在 jdk 17 下构建的，如果在 jdk 1.8 下运行会出现这个错。
换个  jdk 17 试试。

**Comment by marsapolo** [comment]
好的，谢谢，我看文章里面写JDK1.8，还特意用1.8试的

**Comment by marsapolo** [comment]
> 

您好，我使用JDK17和18重新在MAC上跑，还是报相同的错误。

**Comment by marsapolo** [comment]
> 
删除 data 目录重试就可以了。谢谢，查到的也是你在别的地方的回复。

**Comment by codefollower** [comment]
这个问题是在 jdk 17 下打包引起的，几天前我升级 maven-compiler-plugin，配置<release>8</release>参数后在 jdk 17 下打包也能在 jdk 1.8 跑了。 [修复日志](https://github.com/lealone/Lealone/commit/c9e08d2c7d2e2b2bd951582d2a7003239d2f78c7)

lealone-5.0.0.zip 和 lealone-5.0.0.tar.gz 我没有更新

可以更新一下 lealone 的源代码，然后在本机上也可以构建出最新版本的 lealone，
构建文档可以看这里： [从源码构建Lealone](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BB%8E%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BALealone.md)
