### ISSUE TITLE
IDEA社区版，运行VoiceSqlScriptTest报错 

### ISSUE THREAD

**Issue by jiliapp** [lealone/Lealone-Docs#6]
使用Lealone开发单机和分布式微服务应用.md

IDEA社区版，运行VoiceSqlScriptTest报错。路径不对
````
Exception in thread "main" org.lealone.common.exceptions.JdbcSQLException: IO Exception: "java.io.FileNotFoundException: ..\voice-dal\src\main\resources\tables.sql (系统找不到指定的路径。)"; "../voice-dal/src/main/resources/tables.sql"; SQL statement:
RUNSCRIPT FROM '../voice-dal/src/main/resources/tables.sql' [90031-0]
	at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:340)
	at org.lealone.common.exceptions.DbException.get(DbException.java:161)
	at org.lealone.common.exceptions.DbException.convertIOException(DbException.java:326)
	at org.lealone.sql.dml.ScriptBase.openInput(ScriptBase.java:164)
	at org.lealone.sql.dml.RunScript.update(RunScript.java:53)
	at org.lealone.sql.executor.DefaultYieldableLocalUpdate.executeInternal(DefaultYieldableLocalUpdate.java:22)
	at org.lealone.sql.executor.YieldableBase.run(YieldableBase.java:109)
	at org.lealone.db.session.ServerSession$YieldableCommand.run(ServerSession.java:1501)
	at org.lealone.server.Scheduler.executeNextStatement(Scheduler.java:232)
	at org.lealone.server.Scheduler.run(Scheduler.java:103)
Caused by: java.io.FileNotFoundException: ..\voice-dal\src\main\resources\tables.sql (系统找不到指定的路径。)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at org.lealone.storage.fs.FilePathDisk.newInputStream(FilePathDisk.java:313)
	at org.lealone.storage.fs.FileUtils.newInputStream(FileUtils.java:217)
	at org.lealone.sql.dml.ScriptBase.openInput(ScriptBase.java:162)
	... 6 more

	at org.lealone.net.TransferConnection.parseError(TransferConnection.java:66)
	at org.lealone.net.TcpClientConnection.handleResponse(TcpClientConnection.java:101)
	at org.lealone.net.TransferConnection.handle(TransferConnection.java:123)
	at org.lealone.net.nio.NioEventLoop.read(NioEventLoop.java:208)
	at org.lealone.net.nio.NioEventLoopClient.run(NioEventLoopClient.java:74)
	at org.lealone.net.nio.NioEventLoopClient.lambda$0(NioEventLoopClient.java:46)
	at java.base/java.lang.Thread.run(Thread.java:833)

````

楼主能否支持IDEA开发？
系统环境：window11

**Comment by codefollower** [comment]
你打开VoiceSqlScript那个类，修改一下默认目录就可以了，或者你在里面 new File(".") 看看当前目录是什么，eclipse 跟 idea 的工作目录可能不同。

**Comment by codefollower** [comment]
问题已经修复了，我在 IDEA 下能正常测试运行了，重新下载 create-lealone-app-5.0.0.jar，然后删除原来的应用，重新创建一个新的就可以了。

感谢报告问题。

**Comment by jiliapp** [comment]
已验证，IDEA运行环境已正常。
